2018-06-26 19:17:46,152: WARNING *** stderr: Error in sys.exitfunc:
2018-06-26 19:17:46,153: WARNING *** stderr: Traceback (most recent call last):
2018-06-26 19:17:46,153: WARNING *** stderr:   File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
2018-06-26 19:17:46,153: WARNING *** stderr:     func(*targs, **kargs)
2018-06-26 19:17:46,153: WARNING *** stderr:   File "/usr/lib/python2.7/multiprocessing/util.py", line 325, in _exit_function
2018-06-26 19:17:46,153: WARNING *** stderr:     p.join()
2018-06-26 19:17:46,154: WARNING *** stderr:   File "/usr/lib/python2.7/multiprocessing/process.py", line 145, in join
2018-06-26 19:17:46,154: WARNING *** stderr:     res = self._popen.wait(timeout)
2018-06-26 19:17:46,154: WARNING *** stderr:   File "/usr/lib/python2.7/multiprocessing/forking.py", line 154, in wait
2018-06-26 19:17:46,154: WARNING *** stderr:     return self.poll(0)
2018-06-26 19:17:46,154: WARNING *** stderr:   File "/usr/lib/python2.7/multiprocessing/forking.py", line 135, in poll
2018-06-26 19:17:46,154: WARNING *** stderr:     pid, sts = os.waitpid(self.pid, flag)
2018-06-26 19:17:46,155: WARNING *** stderr: KeyboardInterrupt
